# Self-signed internal TLS cert for ddns.witschger.home (signed by `localca`)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ddns-witschger-home
  namespace: cloudflare-ddns
spec:
  secretName: ddns-witschger-home-tls
  duration: 8760h        # 1 year
  renewBefore: 720h      # 30 days before expiry
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: localca
    kind: ClusterIssuer
  dnsNames:
    - ddns.witschger.home
