# Standard Ingress on traefik-internal.
# TLS cert is auto-managed by cert-manager via the cluster-issuer annotation
# (see Certificate object auto-created in cert-manager logs).
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudflare-ddns
  namespace: cloudflare-ddns
  annotations:
    cert-manager.io/cluster-issuer: localca
spec:
  ingressClassName: traefik-internal
  rules:
    - host: ddns.witschger.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloudflare-ddns
                port:
                  number: 8080
  tls:
    - hosts:
        - ddns.witschger.home
      secretName: ddns-witschger-home-tls
