blank_issues_enabled: true
contact_links:
  - name: Question / discussion
    url: https://github.com/The-Pizza/Cloudflare-DDNS/discussions
    about: For general questions, please open a Discussion instead of an Issue.
